muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1067.fasta -out /home/breena/Documents/Project/align/lmo1067.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0995.fasta -out /home/breena/Documents/Project/align/lmo0995.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Pfmt.fasta -out /home/breena/Documents/Project/align/fmt.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2153.fasta -out /home/breena/Documents/Project/align/lmo2153.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2742.fasta -out /home/breena/Documents/Project/align/lmo2742.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1698.fasta -out /home/breena/Documents/Project/align/lmo1698.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2573.fasta -out /home/breena/Documents/Project/align/lmo2573.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0642.fasta -out /home/breena/Documents/Project/align/lmo0642.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2238.fasta -out /home/breena/Documents/Project/align/lmo2238.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0756.fasta -out /home/breena/Documents/Project/align/lmo0756.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1518.fasta -out /home/breena/Documents/Project/align/lmo1518.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1372.fasta -out /home/breena/Documents/Project/align/lmo1372.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0458.fasta -out /home/breena/Documents/Project/align/lmo0458.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1967.fasta -out /home/breena/Documents/Project/align/lmo1967.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0539.fasta -out /home/breena/Documents/Project/align/lmo0539.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0880.fasta -out /home/breena/Documents/Project/align/lmo0880.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PtrxB.fasta -out /home/breena/Documents/Project/align/trxB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1667.fasta -out /home/breena/Documents/Project/align/lmo1667.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0313.fasta -out /home/breena/Documents/Project/align/lmo0313.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0935.fasta -out /home/breena/Documents/Project/align/lmo0935.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1212.fasta -out /home/breena/Documents/Project/align/lmo1212.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0360.fasta -out /home/breena/Documents/Project/align/lmo0360.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2009.fasta -out /home/breena/Documents/Project/align/lmo2009.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2354.fasta -out /home/breena/Documents/Project/align/lmo2354.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0794.fasta -out /home/breena/Documents/Project/align/lmo0794.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1606.fasta -out /home/breena/Documents/Project/align/lmo1606.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2063.fasta -out /home/breena/Documents/Project/align/lmo2063.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PmutS.fasta -out /home/breena/Documents/Project/align/mutS.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0211.fasta -out /home/breena/Documents/Project/align/lmo0211.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0585.fasta -out /home/breena/Documents/Project/align/lmo0585.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0379.fasta -out /home/breena/Documents/Project/align/lmo0379.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1421.fasta -out /home/breena/Documents/Project/align/lmo1421.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1366.fasta -out /home/breena/Documents/Project/align/lmo1366.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2287.fasta -out /home/breena/Documents/Project/align/lmo2287.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PgyrA.fasta -out /home/breena/Documents/Project/align/gyrA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0265.fasta -out /home/breena/Documents/Project/align/lmo0265.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0171.fasta -out /home/breena/Documents/Project/align/lmo0171.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0901.fasta -out /home/breena/Documents/Project/align/lmo0901.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PltrC.fasta -out /home/breena/Documents/Project/align/ltrC.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0610.fasta -out /home/breena/Documents/Project/align/lmo0610.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PgadT1.fasta -out /home/breena/Documents/Project/align/gadT1.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrpoC.fasta -out /home/breena/Documents/Project/align/rpoC.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PlisK.fasta -out /home/breena/Documents/Project/align/lisK.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PaspB.fasta -out /home/breena/Documents/Project/align/aspB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PminD.fasta -out /home/breena/Documents/Project/align/minD.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2835.fasta -out /home/breena/Documents/Project/align/lmo2835.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PsrtB.fasta -out /home/breena/Documents/Project/align/srtB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2173.fasta -out /home/breena/Documents/Project/align/lmo2173.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0679.fasta -out /home/breena/Documents/Project/align/lmo0679.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2497.fasta -out /home/breena/Documents/Project/align/lmo2497.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2520.fasta -out /home/breena/Documents/Project/align/lmo2520.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0049.fasta -out /home/breena/Documents/Project/align/lmo0049.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0750.fasta -out /home/breena/Documents/Project/align/lmo0750.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrpmC.fasta -out /home/breena/Documents/Project/align/rpmC.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PclpC.fasta -out /home/breena/Documents/Project/align/clpC.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2210.fasta -out /home/breena/Documents/Project/align/lmo2210.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0634.fasta -out /home/breena/Documents/Project/align/lmo0634.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1271.fasta -out /home/breena/Documents/Project/align/lmo1271.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2031.fasta -out /home/breena/Documents/Project/align/lmo2031.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2135.fasta -out /home/breena/Documents/Project/align/lmo2135.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2592.fasta -out /home/breena/Documents/Project/align/lmo2592.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0415.fasta -out /home/breena/Documents/Project/align/lmo0415.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0594.fasta -out /home/breena/Documents/Project/align/lmo0594.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1044.fasta -out /home/breena/Documents/Project/align/lmo1044.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2578.fasta -out /home/breena/Documents/Project/align/lmo2578.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1822.fasta -out /home/breena/Documents/Project/align/lmo1822.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2400.fasta -out /home/breena/Documents/Project/align/lmo2400.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1190.fasta -out /home/breena/Documents/Project/align/lmo1190.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1282.fasta -out /home/breena/Documents/Project/align/lmo1282.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PglnA.fasta -out /home/breena/Documents/Project/align/glnA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0658.fasta -out /home/breena/Documents/Project/align/lmo0658.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1435.fasta -out /home/breena/Documents/Project/align/lmo1435.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2281.fasta -out /home/breena/Documents/Project/align/lmo2281.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1261.fasta -out /home/breena/Documents/Project/align/lmo1261.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrpsO.fasta -out /home/breena/Documents/Project/align/rpsO.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1878.fasta -out /home/breena/Documents/Project/align/lmo1878.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1639.fasta -out /home/breena/Documents/Project/align/lmo1639.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0574.fasta -out /home/breena/Documents/Project/align/lmo0574.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0179.fasta -out /home/breena/Documents/Project/align/lmo0179.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0040.fasta -out /home/breena/Documents/Project/align/lmo0040.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0584.fasta -out /home/breena/Documents/Project/align/lmo0584.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1576.fasta -out /home/breena/Documents/Project/align/lmo1576.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PftsX.fasta -out /home/breena/Documents/Project/align/ftsX.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0602.fasta -out /home/breena/Documents/Project/align/lmo0602.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0545.fasta -out /home/breena/Documents/Project/align/lmo0545.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0596.fasta -out /home/breena/Documents/Project/align/lmo0596.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0144.fasta -out /home/breena/Documents/Project/align/lmo0144.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2418.fasta -out /home/breena/Documents/Project/align/lmo2418.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2440.fasta -out /home/breena/Documents/Project/align/lmo2440.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0329.fasta -out /home/breena/Documents/Project/align/lmo0329.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2511.fasta -out /home/breena/Documents/Project/align/lmo2511.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2431.fasta -out /home/breena/Documents/Project/align/lmo2431.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0367.fasta -out /home/breena/Documents/Project/align/lmo0367.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0515.fasta -out /home/breena/Documents/Project/align/lmo0515.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2567.fasta -out /home/breena/Documents/Project/align/lmo2567.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2075.fasta -out /home/breena/Documents/Project/align/lmo2075.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0637.fasta -out /home/breena/Documents/Project/align/lmo0637.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2436.fasta -out /home/breena/Documents/Project/align/lmo2436.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PmurG.fasta -out /home/breena/Documents/Project/align/murG.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PcbiP.fasta -out /home/breena/Documents/Project/align/cbiP.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PqoxA.fasta -out /home/breena/Documents/Project/align/qoxA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2454.fasta -out /home/breena/Documents/Project/align/lmo2454.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PtufA.fasta -out /home/breena/Documents/Project/align/tufA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2085.fasta -out /home/breena/Documents/Project/align/lmo2085.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrpoD.fasta -out /home/breena/Documents/Project/align/rpoD.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1604.fasta -out /home/breena/Documents/Project/align/lmo1604.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PpyrG.fasta -out /home/breena/Documents/Project/align/pyrG.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0907.fasta -out /home/breena/Documents/Project/align/lmo0907.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PsigB.fasta -out /home/breena/Documents/Project/align/sigB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1390.fasta -out /home/breena/Documents/Project/align/lmo1390.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1495.fasta -out /home/breena/Documents/Project/align/lmo1495.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1140.fasta -out /home/breena/Documents/Project/align/lmo1140.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2589.fasta -out /home/breena/Documents/Project/align/lmo2589.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0097.fasta -out /home/breena/Documents/Project/align/lmo0097.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1580.fasta -out /home/breena/Documents/Project/align/lmo1580.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0221.fasta -out /home/breena/Documents/Project/align/lmo0221.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1223.fasta -out /home/breena/Documents/Project/align/lmo1223.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1163.fasta -out /home/breena/Documents/Project/align/lmo1163.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0405.fasta -out /home/breena/Documents/Project/align/lmo0405.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0377.fasta -out /home/breena/Documents/Project/align/lmo0377.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1930.fasta -out /home/breena/Documents/Project/align/lmo1930.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0534.fasta -out /home/breena/Documents/Project/align/lmo0534.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1933.fasta -out /home/breena/Documents/Project/align/lmo1933.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0283.fasta -out /home/breena/Documents/Project/align/lmo0283.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0677.fasta -out /home/breena/Documents/Project/align/lmo0677.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1744.fasta -out /home/breena/Documents/Project/align/lmo1744.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PctaB.fasta -out /home/breena/Documents/Project/align/ctaB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0911.fasta -out /home/breena/Documents/Project/align/lmo0911.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1830.fasta -out /home/breena/Documents/Project/align/lmo1830.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0422.fasta -out /home/breena/Documents/Project/align/lmo0422.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0712.fasta -out /home/breena/Documents/Project/align/lmo0712.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2696.fasta -out /home/breena/Documents/Project/align/lmo2696.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PinlA.fasta -out /home/breena/Documents/Project/align/inlA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2721.fasta -out /home/breena/Documents/Project/align/lmo2721.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PmreC.fasta -out /home/breena/Documents/Project/align/mreC.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrplK.fasta -out /home/breena/Documents/Project/align/rplK.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2783.fasta -out /home/breena/Documents/Project/align/lmo2783.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1815.fasta -out /home/breena/Documents/Project/align/lmo1815.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Piap.fasta -out /home/breena/Documents/Project/align/iap.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0356.fasta -out /home/breena/Documents/Project/align/lmo0356.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0589.fasta -out /home/breena/Documents/Project/align/lmo0589.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0994.fasta -out /home/breena/Documents/Project/align/lmo0994.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1650.fasta -out /home/breena/Documents/Project/align/lmo1650.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2312.fasta -out /home/breena/Documents/Project/align/lmo2312.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2490.fasta -out /home/breena/Documents/Project/align/lmo2490.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0035.fasta -out /home/breena/Documents/Project/align/lmo0035.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0724.fasta -out /home/breena/Documents/Project/align/lmo0724.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PpyrAa.fasta -out /home/breena/Documents/Project/align/pyrAa.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2485.fasta -out /home/breena/Documents/Project/align/lmo2485.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2565.fasta -out /home/breena/Documents/Project/align/lmo2565.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0541.fasta -out /home/breena/Documents/Project/align/lmo0541.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2305.fasta -out /home/breena/Documents/Project/align/lmo2305.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2271.fasta -out /home/breena/Documents/Project/align/lmo2271.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PspxA.fasta -out /home/breena/Documents/Project/align/spxA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0315.fasta -out /home/breena/Documents/Project/align/lmo0315.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0303.fasta -out /home/breena/Documents/Project/align/lmo0303.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1375.fasta -out /home/breena/Documents/Project/align/lmo1375.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PclpP.fasta -out /home/breena/Documents/Project/align/clpP.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2387.fasta -out /home/breena/Documents/Project/align/lmo2387.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2588.fasta -out /home/breena/Documents/Project/align/lmo2588.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_ParcA.fasta -out /home/breena/Documents/Project/align/arcA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PgalE.fasta -out /home/breena/Documents/Project/align/galE.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0850.fasta -out /home/breena/Documents/Project/align/lmo0850.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1155.fasta -out /home/breena/Documents/Project/align/lmo1155.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1975.fasta -out /home/breena/Documents/Project/align/lmo1975.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0739.fasta -out /home/breena/Documents/Project/align/lmo0739.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0629.fasta -out /home/breena/Documents/Project/align/lmo0629.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PpyrAB.fasta -out /home/breena/Documents/Project/align/pyrAB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PuhpT.fasta -out /home/breena/Documents/Project/align/uhpT.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0956.fasta -out /home/breena/Documents/Project/align/lmo0956.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2673.fasta -out /home/breena/Documents/Project/align/lmo2673.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0669.fasta -out /home/breena/Documents/Project/align/lmo0669.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1724.fasta -out /home/breena/Documents/Project/align/lmo1724.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2360.fasta -out /home/breena/Documents/Project/align/lmo2360.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0953.fasta -out /home/breena/Documents/Project/align/lmo0953.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2748.fasta -out /home/breena/Documents/Project/align/lmo2748.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1713.fasta -out /home/breena/Documents/Project/align/lmo1713.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0688.fasta -out /home/breena/Documents/Project/align/lmo0688.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2044.fasta -out /home/breena/Documents/Project/align/lmo2044.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrplM.fasta -out /home/breena/Documents/Project/align/rplM.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0184.fasta -out /home/breena/Documents/Project/align/lmo0184.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2724.fasta -out /home/breena/Documents/Project/align/lmo2724.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0398.fasta -out /home/breena/Documents/Project/align/lmo0398.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1304.fasta -out /home/breena/Documents/Project/align/lmo1304.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2264.fasta -out /home/breena/Documents/Project/align/lmo2264.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2460.fasta -out /home/breena/Documents/Project/align/lmo2460.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1021.fasta -out /home/breena/Documents/Project/align/lmo1021.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0071.fasta -out /home/breena/Documents/Project/align/lmo0071.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0110.fasta -out /home/breena/Documents/Project/align/lmo0110.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Pbsh.fasta -out /home/breena/Documents/Project/align/bsh.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrecR.fasta -out /home/breena/Documents/Project/align/recR.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2472.fasta -out /home/breena/Documents/Project/align/lmo2472.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0325.fasta -out /home/breena/Documents/Project/align/lmo0325.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2132.fasta -out /home/breena/Documents/Project/align/lmo2132.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1613.fasta -out /home/breena/Documents/Project/align/lmo1613.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0514.fasta -out /home/breena/Documents/Project/align/lmo0514.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PsepA.fasta -out /home/breena/Documents/Project/align/sepA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2353.fasta -out /home/breena/Documents/Project/align/lmo2353.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1789.fasta -out /home/breena/Documents/Project/align/lmo1789.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1151.fasta -out /home/breena/Documents/Project/align/lmo1151.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0631.fasta -out /home/breena/Documents/Project/align/lmo0631.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2586.fasta -out /home/breena/Documents/Project/align/lmo2586.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0100.fasta -out /home/breena/Documents/Project/align/lmo0100.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PresD.fasta -out /home/breena/Documents/Project/align/resD.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1046.fasta -out /home/breena/Documents/Project/align/lmo1046.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PgltX.fasta -out /home/breena/Documents/Project/align/gltX.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1583.fasta -out /home/breena/Documents/Project/align/lmo1583.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2110.fasta -out /home/breena/Documents/Project/align/lmo2110.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0129.fasta -out /home/breena/Documents/Project/align/lmo0129.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PmreD.fasta -out /home/breena/Documents/Project/align/mreD.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2298.fasta -out /home/breena/Documents/Project/align/lmo2298.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2386.fasta -out /home/breena/Documents/Project/align/lmo2386.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0876.fasta -out /home/breena/Documents/Project/align/lmo0876.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2483.fasta -out /home/breena/Documents/Project/align/lmo2483.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0993.fasta -out /home/breena/Documents/Project/align/lmo0993.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0336.fasta -out /home/breena/Documents/Project/align/lmo0336.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0314.fasta -out /home/breena/Documents/Project/align/lmo0314.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2795.fasta -out /home/breena/Documents/Project/align/lmo2795.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2670.fasta -out /home/breena/Documents/Project/align/lmo2670.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PackA.fasta -out /home/breena/Documents/Project/align/ackA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0153.fasta -out /home/breena/Documents/Project/align/lmo0153.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0937.fasta -out /home/breena/Documents/Project/align/lmo0937.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Pldh.fasta -out /home/breena/Documents/Project/align/ldh.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0105.fasta -out /home/breena/Documents/Project/align/lmo0105.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0813.fasta -out /home/breena/Documents/Project/align/lmo0813.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1977.fasta -out /home/breena/Documents/Project/align/lmo1977.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Ppfk.fasta -out /home/breena/Documents/Project/align/pfk.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1620.fasta -out /home/breena/Documents/Project/align/lmo1620.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Psod.fasta -out /home/breena/Documents/Project/align/sod.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1127.fasta -out /home/breena/Documents/Project/align/lmo1127.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1410.fasta -out /home/breena/Documents/Project/align/lmo1410.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1883.fasta -out /home/breena/Documents/Project/align/lmo1883.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2593.fasta -out /home/breena/Documents/Project/align/lmo2593.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0267.fasta -out /home/breena/Documents/Project/align/lmo0267.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1616.fasta -out /home/breena/Documents/Project/align/lmo1616.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0579.fasta -out /home/breena/Documents/Project/align/lmo0579.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1921.fasta -out /home/breena/Documents/Project/align/lmo1921.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrplU.fasta -out /home/breena/Documents/Project/align/rplU.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2361.fasta -out /home/breena/Documents/Project/align/lmo2361.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrpmD.fasta -out /home/breena/Documents/Project/align/rpmD.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1694.fasta -out /home/breena/Documents/Project/align/lmo1694.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2377.fasta -out /home/breena/Documents/Project/align/lmo2377.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1466.fasta -out /home/breena/Documents/Project/align/lmo1466.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2230.fasta -out /home/breena/Documents/Project/align/lmo2230.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2494.fasta -out /home/breena/Documents/Project/align/lmo2494.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2391.fasta -out /home/breena/Documents/Project/align/lmo2391.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrplR.fasta -out /home/breena/Documents/Project/align/rplR.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0051.fasta -out /home/breena/Documents/Project/align/lmo0051.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrpsH.fasta -out /home/breena/Documents/Project/align/rpsH.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PcbiA.fasta -out /home/breena/Documents/Project/align/cbiA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0524.fasta -out /home/breena/Documents/Project/align/lmo0524.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2695.fasta -out /home/breena/Documents/Project/align/lmo2695.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0621.fasta -out /home/breena/Documents/Project/align/lmo0621.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0151.fasta -out /home/breena/Documents/Project/align/lmo0151.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrsbV.fasta -out /home/breena/Documents/Project/align/rsbV.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0763.fasta -out /home/breena/Documents/Project/align/lmo0763.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0507.fasta -out /home/breena/Documents/Project/align/lmo0507.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0796.fasta -out /home/breena/Documents/Project/align/lmo0796.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0700.fasta -out /home/breena/Documents/Project/align/lmo0700.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0767.fasta -out /home/breena/Documents/Project/align/lmo0767.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0551.fasta -out /home/breena/Documents/Project/align/lmo0551.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PdltA.fasta -out /home/breena/Documents/Project/align/dltA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0321.fasta -out /home/breena/Documents/Project/align/lmo0321.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Phly.fasta -out /home/breena/Documents/Project/align/hly.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0187.fasta -out /home/breena/Documents/Project/align/lmo0187.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0019.fasta -out /home/breena/Documents/Project/align/lmo0019.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2584.fasta -out /home/breena/Documents/Project/align/lmo2584.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0133.fasta -out /home/breena/Documents/Project/align/lmo0133.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0784.fasta -out /home/breena/Documents/Project/align/lmo0784.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PlemA.fasta -out /home/breena/Documents/Project/align/lemA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0527.fasta -out /home/breena/Documents/Project/align/lmo0527.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0407.fasta -out /home/breena/Documents/Project/align/lmo0407.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1433.fasta -out /home/breena/Documents/Project/align/lmo1433.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1539.fasta -out /home/breena/Documents/Project/align/lmo1539.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PprfA.fasta -out /home/breena/Documents/Project/align/prfA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1182.fasta -out /home/breena/Documents/Project/align/lmo1182.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2848.fasta -out /home/breena/Documents/Project/align/lmo2848.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0695.fasta -out /home/breena/Documents/Project/align/lmo0695.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0052.fasta -out /home/breena/Documents/Project/align/lmo0052.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0633.fasta -out /home/breena/Documents/Project/align/lmo0633.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2496.fasta -out /home/breena/Documents/Project/align/lmo2496.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PmecA.fasta -out /home/breena/Documents/Project/align/mecA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PcdsA.fasta -out /home/breena/Documents/Project/align/cdsA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2339.fasta -out /home/breena/Documents/Project/align/lmo2339.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1043.fasta -out /home/breena/Documents/Project/align/lmo1043.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0034.fasta -out /home/breena/Documents/Project/align/lmo0034.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PdnaG.fasta -out /home/breena/Documents/Project/align/dnaG.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PinlH.fasta -out /home/breena/Documents/Project/align/inlH.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2464.fasta -out /home/breena/Documents/Project/align/lmo2464.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0863.fasta -out /home/breena/Documents/Project/align/lmo0863.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0394.fasta -out /home/breena/Documents/Project/align/lmo0394.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2184.fasta -out /home/breena/Documents/Project/align/lmo2184.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0904.fasta -out /home/breena/Documents/Project/align/lmo0904.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PbvrB.fasta -out /home/breena/Documents/Project/align/bvrB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2095.fasta -out /home/breena/Documents/Project/align/lmo2095.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2775.fasta -out /home/breena/Documents/Project/align/lmo2775.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0197.fasta -out /home/breena/Documents/Project/align/lmo0197.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0137.fasta -out /home/breena/Documents/Project/align/lmo0137.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2311.fasta -out /home/breena/Documents/Project/align/lmo2311.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2827.fasta -out /home/breena/Documents/Project/align/lmo2827.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2174.fasta -out /home/breena/Documents/Project/align/lmo2174.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2850.fasta -out /home/breena/Documents/Project/align/lmo2850.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PtopB.fasta -out /home/breena/Documents/Project/align/topB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PcbiQ.fasta -out /home/breena/Documents/Project/align/cbiQ.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0338.fasta -out /home/breena/Documents/Project/align/lmo0338.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1077.fasta -out /home/breena/Documents/Project/align/lmo1077.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2205.fasta -out /home/breena/Documents/Project/align/lmo2205.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2697.fasta -out /home/breena/Documents/Project/align/lmo2697.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1920.fasta -out /home/breena/Documents/Project/align/lmo1920.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0748.fasta -out /home/breena/Documents/Project/align/lmo0748.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2186.fasta -out /home/breena/Documents/Project/align/lmo2186.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1018.fasta -out /home/breena/Documents/Project/align/lmo1018.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2146.fasta -out /home/breena/Documents/Project/align/lmo2146.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0773.fasta -out /home/breena/Documents/Project/align/lmo0773.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0373.fasta -out /home/breena/Documents/Project/align/lmo0373.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2124.fasta -out /home/breena/Documents/Project/align/lmo2124.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2213.fasta -out /home/breena/Documents/Project/align/lmo2213.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1666.fasta -out /home/breena/Documents/Project/align/lmo1666.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1047.fasta -out /home/breena/Documents/Project/align/lmo1047.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2826.fasta -out /home/breena/Documents/Project/align/lmo2826.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1253.fasta -out /home/breena/Documents/Project/align/lmo1253.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1339.fasta -out /home/breena/Documents/Project/align/lmo1339.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PatpI.fasta -out /home/breena/Documents/Project/align/atpI.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0554.fasta -out /home/breena/Documents/Project/align/lmo0554.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0460.fasta -out /home/breena/Documents/Project/align/lmo0460.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1241.fasta -out /home/breena/Documents/Project/align/lmo1241.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1963.fasta -out /home/breena/Documents/Project/align/lmo1963.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1082.fasta -out /home/breena/Documents/Project/align/lmo1082.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2010.fasta -out /home/breena/Documents/Project/align/lmo2010.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1757.fasta -out /home/breena/Documents/Project/align/lmo1757.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2466.fasta -out /home/breena/Documents/Project/align/lmo2466.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PpyrP.fasta -out /home/breena/Documents/Project/align/pyrP.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0523.fasta -out /home/breena/Documents/Project/align/lmo0523.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PatpF.fasta -out /home/breena/Documents/Project/align/atpF.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1843.fasta -out /home/breena/Documents/Project/align/lmo1843.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2550.fasta -out /home/breena/Documents/Project/align/lmo2550.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0429.fasta -out /home/breena/Documents/Project/align/lmo0429.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2042.fasta -out /home/breena/Documents/Project/align/lmo2042.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1013.fasta -out /home/breena/Documents/Project/align/lmo1013.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PinfB.fasta -out /home/breena/Documents/Project/align/infB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1880.fasta -out /home/breena/Documents/Project/align/lmo1880.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2188.fasta -out /home/breena/Documents/Project/align/lmo2188.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2672.fasta -out /home/breena/Documents/Project/align/lmo2672.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0274.fasta -out /home/breena/Documents/Project/align/lmo0274.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0683.fasta -out /home/breena/Documents/Project/align/lmo0683.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1857.fasta -out /home/breena/Documents/Project/align/lmo1857.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Ppgi.fasta -out /home/breena/Documents/Project/align/pgi.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0439.fasta -out /home/breena/Documents/Project/align/lmo0439.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PbvrA.fasta -out /home/breena/Documents/Project/align/bvrA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PcysS.fasta -out /home/breena/Documents/Project/align/cysS.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1148.fasta -out /home/breena/Documents/Project/align/lmo1148.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0987.fasta -out /home/breena/Documents/Project/align/lmo0987.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0310.fasta -out /home/breena/Documents/Project/align/lmo0310.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0832.fasta -out /home/breena/Documents/Project/align/lmo0832.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2707.fasta -out /home/breena/Documents/Project/align/lmo2707.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1283.fasta -out /home/breena/Documents/Project/align/lmo1283.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PbetL.fasta -out /home/breena/Documents/Project/align/betL.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Ppta.fasta -out /home/breena/Documents/Project/align/pta.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2763.fasta -out /home/breena/Documents/Project/align/lmo2763.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0387.fasta -out /home/breena/Documents/Project/align/lmo0387.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2773.fasta -out /home/breena/Documents/Project/align/lmo2773.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Phfq.fasta -out /home/breena/Documents/Project/align/hfq.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PphoP.fasta -out /home/breena/Documents/Project/align/phoP.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2358.fasta -out /home/breena/Documents/Project/align/lmo2358.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1852.fasta -out /home/breena/Documents/Project/align/lmo1852.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2453.fasta -out /home/breena/Documents/Project/align/lmo2453.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1992.fasta -out /home/breena/Documents/Project/align/lmo1992.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1655.fasta -out /home/breena/Documents/Project/align/lmo1655.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1188.fasta -out /home/breena/Documents/Project/align/lmo1188.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2130.fasta -out /home/breena/Documents/Project/align/lmo2130.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2740.fasta -out /home/breena/Documents/Project/align/lmo2740.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0438.fasta -out /home/breena/Documents/Project/align/lmo0438.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1438.fasta -out /home/breena/Documents/Project/align/lmo1438.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2668.fasta -out /home/breena/Documents/Project/align/lmo2668.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0654.fasta -out /home/breena/Documents/Project/align/lmo0654.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0593.fasta -out /home/breena/Documents/Project/align/lmo0593.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0504.fasta -out /home/breena/Documents/Project/align/lmo0504.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PpurM.fasta -out /home/breena/Documents/Project/align/purM.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2269.fasta -out /home/breena/Documents/Project/align/lmo2269.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2158.fasta -out /home/breena/Documents/Project/align/lmo2158.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PdeoD.fasta -out /home/breena/Documents/Project/align/deoD.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0647.fasta -out /home/breena/Documents/Project/align/lmo0647.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2097.fasta -out /home/breena/Documents/Project/align/lmo2097.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1226.fasta -out /home/breena/Documents/Project/align/lmo1226.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1526.fasta -out /home/breena/Documents/Project/align/lmo1526.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1024.fasta -out /home/breena/Documents/Project/align/lmo1024.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PcomEC.fasta -out /home/breena/Documents/Project/align/comEC.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0072.fasta -out /home/breena/Documents/Project/align/lmo0072.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1940.fasta -out /home/breena/Documents/Project/align/lmo1940.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1124.fasta -out /home/breena/Documents/Project/align/lmo1124.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2602.fasta -out /home/breena/Documents/Project/align/lmo2602.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2575.fasta -out /home/breena/Documents/Project/align/lmo2575.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0169.fasta -out /home/breena/Documents/Project/align/lmo0169.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PfbaA.fasta -out /home/breena/Documents/Project/align/fbaA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0528.fasta -out /home/breena/Documents/Project/align/lmo0528.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0496.fasta -out /home/breena/Documents/Project/align/lmo0496.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2831.fasta -out /home/breena/Documents/Project/align/lmo2831.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0648.fasta -out /home/breena/Documents/Project/align/lmo0648.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0780.fasta -out /home/breena/Documents/Project/align/lmo0780.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2219.fasta -out /home/breena/Documents/Project/align/lmo2219.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PsrtA.fasta -out /home/breena/Documents/Project/align/srtA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2175.fasta -out /home/breena/Documents/Project/align/lmo2175.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0990.fasta -out /home/breena/Documents/Project/align/lmo0990.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0913.fasta -out /home/breena/Documents/Project/align/lmo0913.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0628.fasta -out /home/breena/Documents/Project/align/lmo0628.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0885.fasta -out /home/breena/Documents/Project/align/lmo0885.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0380.fasta -out /home/breena/Documents/Project/align/lmo0380.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0869.fasta -out /home/breena/Documents/Project/align/lmo0869.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PpykA.fasta -out /home/breena/Documents/Project/align/pykA.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2012.fasta -out /home/breena/Documents/Project/align/lmo2012.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PtagB.fasta -out /home/breena/Documents/Project/align/tagB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2389.fasta -out /home/breena/Documents/Project/align/lmo2389.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0459.fasta -out /home/breena/Documents/Project/align/lmo0459.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2145.fasta -out /home/breena/Documents/Project/align/lmo2145.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1120.fasta -out /home/breena/Documents/Project/align/lmo1120.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PrsbX.fasta -out /home/breena/Documents/Project/align/rsbX.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1266.fasta -out /home/breena/Documents/Project/align/lmo1266.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2733.fasta -out /home/breena/Documents/Project/align/lmo2733.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PgadT2.fasta -out /home/breena/Documents/Project/align/gadT2.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2156.fasta -out /home/breena/Documents/Project/align/lmo2156.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2365.fasta -out /home/breena/Documents/Project/align/lmo2365.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0037.fasta -out /home/breena/Documents/Project/align/lmo0037.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1340.fasta -out /home/breena/Documents/Project/align/lmo1340.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PpheT.fasta -out /home/breena/Documents/Project/align/pheT.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo0722.fasta -out /home/breena/Documents/Project/align/lmo0722.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo2014.fasta -out /home/breena/Documents/Project/align/lmo2014.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PgadD3.fasta -out /home/breena/Documents/Project/align/gadD3.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1602.fasta -out /home/breena/Documents/Project/align/lmo1602.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1653.fasta -out /home/breena/Documents/Project/align/lmo1653.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1668.fasta -out /home/breena/Documents/Project/align/lmo1668.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_Plmo1689.fasta -out /home/breena/Documents/Project/align/lmo1689.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PcydB.fasta -out /home/breena/Documents/Project/align/cydB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PplcB.fasta -out /home/breena/Documents/Project/align/plcB.aln -clwstrict
muscle -in /home/breena/Documents/Project/cured_promoter_seqs_unordered/SigB_PopuCA.fasta -out /home/breena/Documents/Project/align/opuCA.aln -clwstrict
